from is_class import is_class

# Sample course list (this should be generated by the parser in another file)
cs_courses = {"C S 1313", "C S 1323", "C S 2334", "C S 2813"}  # Example set

# Test cases
if __name__ == "__main__":
    print(is_class("C S 1313", cs_courses))  # Expected: True
    print(is_class("C S 3000", cs_courses))  # Expected: False
    print(is_class("C S 2334", cs_courses))  # Expected: True
    print(is_class("C S 1111", cs_courses))  # Expected: False
