name: Run Course Extraction and Tests

on:
  workflow_dispatch:  # Manual trigger for demonstration reasons

jobs:
  extract_list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install requests bs4

      - name: Extract possible course list
        run: |
          . venv/bin/activate
          python3 backend/data_extraction/possible_classes.py

      - name: Upload course list output
        uses: actions/upload-artifact@v4
        with:
          name: course-list-output
          path: backend/data_extraction/data/extracted_classes.txt

  test_courses:
    runs-on: ubuntu-latest
    needs: extract_list

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install requests bs4

      - name: Download course list output artifact
        uses: actions/download-artifact@v4
        with:
          name: course-list-output
          path: backend/data_extraction/data/ 

      - name: List files in the directory
        run: |
          ls -R backend/data_extraction/data/
    
      - name: Test course list
        run: |
          . venv/bin/activate
          cd backend/test_cases
          python3 is_class.py

      - name: Deploy to Github Pages
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git checkout main
          git pull origin main
          git add backend/data_extraction/data/extracted_classes.txt
          git commit -m "Updated course list"
          git push https://x-access-token:${{ secrets.GH_ARTIFACT_TK }}@github.com/${{ github.repository }}.git main
