name: Run Hugging Face Model

on:
  workflow_dispatch:  # This allows manual trigger without requiring any inputs

jobs:
  run_hf_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the hf_api_test branch
        uses: actions/checkout@v3
        with:
          ref: 'hf_api_test'  # Hardcode the branch name here

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install requests

      - name: Run the Hugging Face model
        env:
          HF_TW_API: ${{ secrets.HF_TW_API }}  # Use secret in environment variables
        run: |
          . venv/bin/activate
          python hugging_face_test.py  # Ensure this file path is correct
